#pragma once

#include "BaseActivation.h"

#include "ScalarActivation.h"
#include "TensorActivation.h"

#include "ArcTan.h"
#include "BinaryStep.h"
#include "ELU.h"
#include "Exponential.h"
#include "Gaussian.h"
#include "GELU.h"
#include "HardShrink.h"
#include "HardSigmoid.h"
#include "HardSwish.h"
#include "HardTanh.h"
#include "LeakyReLU.h"
#include "Linear.h"
#include "LogSigmoid.h"
#include "Mish.h"
#include "PReLU.h"
#include "ReLU.h"
#include "ReLU6.h"
#include "SELU.h"
#include "Sigmoid.h"
#include "Softplus.h"
#include "SoftShrink.h"
#include "Softsign.h"
#include "SparsePlus.h"
#include "SquarePlus.h"
#include "Swish.h"
#include "_Tanh.h"
#include "TanhShrink.h"

#include "LogSoftmax.h"
#include "Softmax.h"
#include "Sparsemax.h"
