#pragma once

#include "BaseOperation.h"

#include "Abs.h"
#include "Ceil.h"
#include "Clip.h"
#include "Exp.h"
#include "Floor.h"
#include "Log.h"
#include "Mod.h"
#include "Power.h"
#include "Round.h"
#include "Sqrt.h"

#include "Sin.h"
#include "Cos.h"
#include "Tan.h"
#include "Csc.h"
#include "Sec.h"
#include "Cot.h"
#include "Asin.h"
#include "Acos.h"
#include "Atan.h"
#include "Acsc.h"
#include "Asec.h"
#include "Acot.h"

#include "Sinh.h"
#include "Cosh.h"
#include "Tanh.h"
#include "Csch.h"
#include "Sech.h"
#include "Coth.h"
#include "Asinh.h"
#include "Acosh.h"
#include "Atanh.h"
#include "Acsch.h"
#include "Asech.h"
#include "Acoth.h"
